name: build-test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
      - run: bun run build
